# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cuckoo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '5.1'
  pod 'Moya', '~> 14.0'

  # Pods for Cuckoo

  target 'CuckooTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CuckooUITests' do
    # Pods for testing
  end

end
